### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by aelfric-m** [JohannaGaudeck/CatNews_origins#6]
- [x] Switch from FXML to NOFXML or make the GUI scalable
- [x] Rename buttons and fields appropriately
- [x] Add Button "Open Today's File"
- [x] Move saved items to "saved items" pane
- [x] Fields for starting date and end date
- [x] Field for maximum of displayed articles

**Comment by JohannaGaudeck** [comment]
No NOFXML but GUI is scalable
